### PR TITLE
More updates

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
@PiotrMitkowski Have you had a look at it? :)

**Comment by PiotrMitkowski** [comment]
@ThexXTURBOXx I took a quick look, but will do a full review on Monday :)

**Comment by PiotrMitkowski** [comment]
@ThexXTURBOXx I saw in the discussion under my PR that you're going to create a separate one. Do you still want me to review this one here?

**Comment by ThexXTURBOXx** [comment]
If you want, you can do that. However, yes, I will create a separate one after yours is merged :)

**Comment by PiotrMitkowski** [comment]
I'll wait for the other PR then and do a review there, if necessary :) Thanks!

**Pull request closed without merging**
